package com.cencen.luminaluxe.model

import com.cencen.luminaluxe.R

object FakeSkincareDataResource {
    val dummySkincare = listOf(
        Skincare(1, R.drawable.skin_1, "Emina Bright Stuff Serum", 53500, "Bright Stuff Face Serum membantu menggapai kulit impianmu dan melawan 7 masalah kulit kusam! mencerahkan kulit, mengurangi tampilan noda hitam, kulit tampak glowing, dengan aktif anti-pollution yang melindungi kulit dari polusi debu & kotoran, bantu melindungi skin barrier, menjaga kulit tetap sehat dan terhidrasi dengan baik, kulit terasa halus."),
        Skincare(2, R.drawable.skin_2, "Rojukiss Korean Serum", 23000, "Serum perawatan wajah untuk kulit kusam dan warna kulit tidak merata. Diperkaya ekstrak Jeju Lotus, Pomegranate, Glutathione, Vitamin B3 (Niacinamide), dan Witch Hazel. Membantu menutrisi dengan efektif, mencerahkan, meratakan warna kulit, melembutkan dan mengencangkan pori, sehingga kulit tampak lebih cerah, merona, halus dan mulus. Dikembangkan oleh ahli kulit Korea."),
        Skincare(3, R.drawable.skin_3, "Avoskin YSB Toner", 150500, "Salah satu Avoskin YSB serum untuk mencerahkan adalah serum Avoskin Your Skin Bae Salicylic Acid. Manfaat serum Avoskin ini diformulasikan khusus untuk mengatasi masalah jerawat dan blackhead pada kulit. Produk yang satu ini termasuk dalam anti acne dan exfoliating serum."),
        Skincare(4, R.drawable.skin_4, "Wardah Hydra Rose Serum", 135500, "Serum dengan kandungan 72 Hours Hydrating Active dan Rose Oil menghidrasi serta menjaga kelembapan kulit. Diperkaya butiran HydraMoist Micro Gel, gel lembut yang melebur ke setiap lapisan kulit terdalam memberikan kelembapan ekstra sepanjang hari."),
        Skincare(5, R.drawable.skin_5, "Bioderma Sensibio Gel moussant", 308500, "Semua produk BIODERMA diformulasikan di Laboratorium BIODERMA sesuai dengan prinsip-prinsip ekobiologi, yang merupakan pendekatan utama NAOS dalam menghormati ekosistem dan menjaga kesehatan kulit."),
        Skincare(6, R.drawable.skin_6, "Garnier Sakura White", 38000, "Miliki kulit wajah cerah dan kenyal dengan berbagai serum wajah Garnier. Pilihan serum Garnier sangat beragam untuk menjawab kebutuhan kulitmu. Diperkaya dengan bahan-bahan aktif serta ekstrak bahan alami, temukan serum wajah untuk mencerahkan kulitmu."),
        Skincare(7, R.drawable.skin_7, "Senka Perfect Whip", 57000, "Facial foam yang diperkaya dengan Salicylic Acid, varian Perfect Whip Acne Care mampu bersihkan kotoran, sel kulit mati, sebum, sisa makeup yang mengakibatkan jerawat hingga ke pori-pori. Adapun terdapat juga kandungan Kyoto Chamomile Extract yang kaya antioksidan dan antibakteri, yang mencegah terjadinya kerusakan lebih lanjut pada kulit."),
        Skincare(8, R.drawable.skin_8, "Ariul Hydro Vital Watermelon", 79500, "Moisturizing Glow Serum yang mampu untuk menenangkan dan mendinginkan kulit dengan cepat sekaligus menutrisi agar kulit tampak glowing dan cerah."),
        Skincare(9, R.drawable.skin_9, "Scarlett Brightly Ever After", 74500, "Didalam Brightly Ever After Night Cream terdapat kandungan Glutathione, Niacinamide, Natural Vit-C, Hexapeptide-8, Poreaway, Green Caviar dan Aqua Peptide Glow yang dimana bermanfaat sebagai Membantu meningkatkan kelembapan serta elastisitas kulit wajah."),
        Skincare(10, R.drawable.skin_10, "Avoskin YSB Moisturizer", 374500, "Memiliki fungsi utama untuk mencerahkan kulit dan mengurangi bintik hitam pada wajah. Beda sama yang sebelumnya, kalau ini punya kandungan 2% Alpha Arbutin, Multi Probiome, dan Beta Carotene. Dirancang buat kamu yang cari moisturizer Avoskin untuk mencerahkan kulit, menjaga elastisitas, menghidrasi kulit, dan menyamarkan dark spots."),
        Skincare(11, R.drawable.skin_11, "Beauty of Majesty Tone-up Cream", 245600, "Tone-Up Cream yang mengandung vitamin dari ekstrak air mawar yang berlimpah, membuat wajah tampak berseri dan cerah serta tahan lama. Mengandung air mawar Prancis lebih dari 70%, vitamin B12 yang mampu meningkatkan warna kulit, triple hyaluronic acid, ekstrak Peach dan Acerola."),
        Skincare(12, R.drawable.skin_12, "Skintific MSH Niacinamide Moisturizer", 331800, "MSH Niacinamide Brightening Moisture Gel dengan tekstur seringan udara, dapat menyerap dengan cepat dan mengontrol minyak dalam 24 jam. Diformulasikan dengan Novel MSH Niacinamide ekslusif SKINTIFIC yang dikombinasikan dengan dua bahan pencerah yang ringan dan paling efektif yaitu Alpha Arbutin dan Tranexamic Acid, yang mampu mencerahkan dengan signifikan dalam waktu 14 hari. "),
    )
}